mode: dev
prod:
  - botname: Safy
    username: safymanegement_bot
    token: 
      7656524988:AAGn5Xctwb4fWwQ9myU91r6MAcB3jpzfLyA
    about:
      "This is a powerful Telegram Management Bot designed to help admins manage groups easily and securely.
It keeps groups clean, safe, and well-organized with automated moderation tools.

Features:
• Admin-only commands  
• Ban / Mute / Warn system  
• Spam & flood control  
• Welcome messages  
• Fast & lightweight  
• 24×7 online

Made to simplify group management and save admins time.h"
    description:
      "A simple Telegram management bot to help admins manage groups easily.
Supports basic moderation tools to keep groups clean and organized.
  - botname: Safy
    username: safymanegement_bot
    token: 
      7656524988:AAGn5Xctwb4fWwQ9myU91r6MAcB3jpzfLyA
    about:
      "This is a powerful Telegram Management Bot designed to help admins manage groups easily and securely.
It keeps groups clean, safe, and well-organized with automated moderation tools.

Features:
• Admin-only commands  
• Ban / Mute / Warn system  
• Spam & flood control  
• Welcome messages  
• Fast & lightweight  
• 24×7 online

Made to simplify group management and save admins time."
    description:
      "A simple Telegram management bot to help admins manage groups easily.
Supports basic moderation tools to keep groups clean and organized."
